name:                beefheart
version:             0.2.6.0
license:             Apache
license-file:        LICENSE
author:              "Elastic Infra Team"
copyright:           "2020 Elasticsearch, Inc"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/elastic/beefheart#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- data-default
- ekg
- ekg-core
- envy
- http-client
- http-types
- katip
- lens
- lens-aeson
- monad-loops
- mtl
- optparse-applicative
- req
- retry
- rio
- rio-orphans
- safe-exceptions
- scientific
- stm
- text
- time
- unix
- unordered-containers

library:
  source-dirs: src
  default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  ghc-options:
  - -Wall
  - -fno-warn-orphans

executables:
  beefheart:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
    - AutoDeriveTypeable
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - EmptyDataDecls
    - ExistentialQuantification
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MonadFailDesugaring
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - NoImplicitPrelude
    - OverloadedStrings
    - PartialTypeSignatures
    - PatternGuards
    - PolyKinds
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TupleSections
    - TypeFamilies
    - TypeSynonymInstances
    - ViewPatterns
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    - -optP-Wno-nonportable-include-path
    - -fno-warn-orphans
    dependencies:
    - beefheart

tests:
  beefheart-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    - -fno-warn-orphans
    default-extensions:
    - AutoDeriveTypeable
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - EmptyDataDecls
    - ExistentialQuantification
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - MonadFailDesugaring
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - NoImplicitPrelude
    - OverloadedStrings
    - PartialTypeSignatures
    - PatternGuards
    - PolyKinds
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TupleSections
    - TypeFamilies
    - TypeOperators
    - TypeSynonymInstances
    - ViewPatterns
    dependencies:
    - beefheart
    - docker
    - generic-random
    - random
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-text
